// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package datagodb

import (
	"github.com/michaellee8/txtgodb/pkg/data/parser/txt"
	"github.com/michaellee8/txtgodb/pkg/data/sinker/sql"
	"github.com/michaellee8/txtgodb/pkg/schema/parser/csv"
)

// Injectors from wire.go:

func InitializeDataLoader() *DataLoader {
	csvSchemaParser := csv.NewCSVParser()
	textDataParser := txt.NewTextDataParser()
	sqlDataSinker := sql.NewSQLDataSinker()
	dataLoader := NewDataLoader(csvSchemaParser, textDataParser, sqlDataSinker)
	return dataLoader
}
